import type { ReproBundle } from "./types.js";

export function renderJson(bundle: ReproBundle): string {
  return `${JSON.stringify(bundle, null, 2)}\n`;
}

export function renderMarkdown(bundle: ReproBundle): string {
  const lines: string[] = [];
  lines.push("# LogVeil Repro Bundle", "");
  lines.push(`- Generated by: ${bundle.generatedBy}`);
  lines.push(`- Schema version: ${bundle.schemaVersion}`);
  lines.push(`- Created at: ${bundle.createdAt}`);
  lines.push(`- Redaction enabled: ${bundle.redactionEnabled ? "yes" : "no"}`);
  lines.push(`- Files: ${bundle.summary.files}`);
  lines.push(`- Findings: ${bundle.summary.findings} (${bundle.summary.secrets} secret, ${bundle.summary.warnings} warning, ${bundle.summary.info} info)`);
  lines.push("");
  lines.push("## Redaction evidence", "");
  if (bundle.summary.findings === 0) {
    lines.push("No findings.", "");
  } else {
    lines.push("| File | Line | Type | Severity | Evidence | Replacement |");
    lines.push("| --- | ---: | --- | --- | --- | --- |");
    for (const file of bundle.files) {
      for (const finding of file.findings) {
        lines.push(`| ${escapeCell(file.path)} | ${finding.line}:${finding.column} | ${finding.type} | ${finding.severity} | ${escapeCell(finding.evidence)} | ${escapeCell(finding.replacement)} |`);
      }
    }
    lines.push("");
  }

  for (const file of bundle.files) {
    lines.push(`## File: ${file.path}`, "");
    lines.push(`- Original bytes: ${file.originalBytes}`);
    lines.push(`- Sanitized bytes: ${file.sanitizedBytes}`);
    lines.push(`- Sanitized SHA-256: ${file.sha256}`);
    lines.push("");
    lines.push("```text");
    lines.push(file.sanitized.replace(/```/g, "`\u200b``"));
    lines.push("```", "");
  }
  return `${lines.join("\n").trimEnd()}\n`;
}

function escapeCell(value: string): string {
  return value.replace(/\|/g, "\\|").replace(/\n/g, "\\n");
}
